name: Auth CD

on:
  workflow_run:
    workflows: ["Auth Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Auth Image
      run: docker pull 842676019334.dkr.ecr.ap-south-1.amazonaws.com/swan/auth:latest

    - name: Stop Previous Auth
      run: |
        docker rm -f auth-container || true

    - name: Create an env file
      run: |
        touch auth.env
        echo "${{ secrets.AUTH_ENV }}" >> auth.env

    - name: Run the new Container
      run: |
        docker run -d -p 127.0.0.1:4000:4000 --name auth-container --env-file=auth.env 842676019334.dkr.ecr.ap-south-1.amazonaws.com/swan/auth:latest

    - name: Remove the env file
      run: |
        rm auth.env
