name: Gateway Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/Gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to AWS ECR
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 842676019334.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build the Docker Image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build server/Gateway/. --tag 842676019334.dkr.ecr.ap-south-1.amazonaws.com/swan-gateway-img:$IMAGE_TAG

    # Step 4: Push the Docker image to AWS ECR
    - name: Push Docker Image to AWS ECR
      run: |
        IMAGE_TAG=$(date +%s)
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.$AWS_REGION.amazonaws.com/swan-gateway-img:$IMAGE_TAG

