name: Wallet Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/Wallet/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to AWS ECR
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-south-1
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 842676019334.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build the Docker Image
      run: |
        docker build server/Wallet/. --tag 842676019334.dkr.ecr.ap-south-1.amazonaws.com/swan/wallet:latest

    - name: Push Docker Image to AWS ECR
      run: |
        docker push 842676019334.dkr.ecr.ap-south-1.amazonaws.com/swan/wallet:latest
